// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/huseyinbabal/kubetag/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockImageRepository is an autogenerated mock type for the ImageRepositoryInterface type
type MockImageRepository struct {
	mock.Mock
}

type MockImageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageRepository) EXPECT() *MockImageRepository_Expecter {
	return &MockImageRepository_Expecter{mock: &_m.Mock}
}

// DeleteImageTag provides a mock function with given fields: resourceType, resourceName, namespace
func (_m *MockImageRepository) DeleteImageTag(resourceType string, resourceName string, namespace string) error {
	ret := _m.Called(resourceType, resourceName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImageTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(resourceType, resourceName, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockImageRepository_DeleteImageTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImageTag'
type MockImageRepository_DeleteImageTag_Call struct {
	*mock.Call
}

// DeleteImageTag is a helper method to define mock.On call
//   - resourceType string
//   - resourceName string
//   - namespace string
func (_e *MockImageRepository_Expecter) DeleteImageTag(resourceType interface{}, resourceName interface{}, namespace interface{}) *MockImageRepository_DeleteImageTag_Call {
	return &MockImageRepository_DeleteImageTag_Call{Call: _e.mock.On("DeleteImageTag", resourceType, resourceName, namespace)}
}

func (_c *MockImageRepository_DeleteImageTag_Call) Run(run func(resourceType string, resourceName string, namespace string)) *MockImageRepository_DeleteImageTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockImageRepository_DeleteImageTag_Call) Return(_a0 error) *MockImageRepository_DeleteImageTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageRepository_DeleteImageTag_Call) RunAndReturn(run func(string, string, string) error) *MockImageRepository_DeleteImageTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllImages provides a mock function with given fields: namespace
func (_m *MockImageRepository) GetAllImages(namespace string) ([]models.ImageInfo, error) {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetAllImages")
	}

	var r0 []models.ImageInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.ImageInfo, error)); ok {
		return rf(namespace)
	}
	if rf, ok := ret.Get(0).(func(string) []models.ImageInfo); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ImageInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageRepository_GetAllImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllImages'
type MockImageRepository_GetAllImages_Call struct {
	*mock.Call
}

// GetAllImages is a helper method to define mock.On call
//   - namespace string
func (_e *MockImageRepository_Expecter) GetAllImages(namespace interface{}) *MockImageRepository_GetAllImages_Call {
	return &MockImageRepository_GetAllImages_Call{Call: _e.mock.On("GetAllImages", namespace)}
}

func (_c *MockImageRepository_GetAllImages_Call) Run(run func(namespace string)) *MockImageRepository_GetAllImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockImageRepository_GetAllImages_Call) Return(_a0 []models.ImageInfo, _a1 error) *MockImageRepository_GetAllImages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageRepository_GetAllImages_Call) RunAndReturn(run func(string) ([]models.ImageInfo, error)) *MockImageRepository_GetAllImages_Call {
	_c.Call.Return(run)
	return _c
}

// GetImageTagHistory provides a mock function with given fields: imageName, namespace
func (_m *MockImageRepository) GetImageTagHistory(imageName string, namespace string) (*models.ImageTagHistory, error) {
	ret := _m.Called(imageName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetImageTagHistory")
	}

	var r0 *models.ImageTagHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*models.ImageTagHistory, error)); ok {
		return rf(imageName, namespace)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.ImageTagHistory); ok {
		r0 = rf(imageName, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ImageTagHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(imageName, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageRepository_GetImageTagHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageTagHistory'
type MockImageRepository_GetImageTagHistory_Call struct {
	*mock.Call
}

// GetImageTagHistory is a helper method to define mock.On call
//   - imageName string
//   - namespace string
func (_e *MockImageRepository_Expecter) GetImageTagHistory(imageName interface{}, namespace interface{}) *MockImageRepository_GetImageTagHistory_Call {
	return &MockImageRepository_GetImageTagHistory_Call{Call: _e.mock.On("GetImageTagHistory", imageName, namespace)}
}

func (_c *MockImageRepository_GetImageTagHistory_Call) Run(run func(imageName string, namespace string)) *MockImageRepository_GetImageTagHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockImageRepository_GetImageTagHistory_Call) Return(_a0 *models.ImageTagHistory, _a1 error) *MockImageRepository_GetImageTagHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageRepository_GetImageTagHistory_Call) RunAndReturn(run func(string, string) (*models.ImageTagHistory, error)) *MockImageRepository_GetImageTagHistory_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertImageTag provides a mock function with given fields: imageName, _a1, tag, resourceType, resourceName, namespace, containerName
func (_m *MockImageRepository) UpsertImageTag(imageName string, _a1 string, tag string, resourceType string, resourceName string, namespace string, containerName string) error {
	ret := _m.Called(imageName, _a1, tag, resourceType, resourceName, namespace, containerName)

	if len(ret) == 0 {
		panic("no return value specified for UpsertImageTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string, string) error); ok {
		r0 = rf(imageName, _a1, tag, resourceType, resourceName, namespace, containerName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockImageRepository_UpsertImageTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertImageTag'
type MockImageRepository_UpsertImageTag_Call struct {
	*mock.Call
}

// UpsertImageTag is a helper method to define mock.On call
//   - imageName string
//   - _a1 string
//   - tag string
//   - resourceType string
//   - resourceName string
//   - namespace string
//   - containerName string
func (_e *MockImageRepository_Expecter) UpsertImageTag(imageName interface{}, _a1 interface{}, tag interface{}, resourceType interface{}, resourceName interface{}, namespace interface{}, containerName interface{}) *MockImageRepository_UpsertImageTag_Call {
	return &MockImageRepository_UpsertImageTag_Call{Call: _e.mock.On("UpsertImageTag", imageName, _a1, tag, resourceType, resourceName, namespace, containerName)}
}

func (_c *MockImageRepository_UpsertImageTag_Call) Run(run func(imageName string, _a1 string, tag string, resourceType string, resourceName string, namespace string, containerName string)) *MockImageRepository_UpsertImageTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *MockImageRepository_UpsertImageTag_Call) Return(_a0 error) *MockImageRepository_UpsertImageTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageRepository_UpsertImageTag_Call) RunAndReturn(run func(string, string, string, string, string, string, string) error) *MockImageRepository_UpsertImageTag_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageRepository creates a new instance of MockImageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageRepository {
	mock := &MockImageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
