// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	k8s "github.com/huseyinbabal/kubetag/internal/k8s"
	mock "github.com/stretchr/testify/mock"

	models "github.com/huseyinbabal/kubetag/internal/models"
)

// MockImageService is an autogenerated mock type for the ImageServiceInterface type
type MockImageService struct {
	mock.Mock
}

type MockImageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageService) EXPECT() *MockImageService_Expecter {
	return &MockImageService_Expecter{mock: &_m.Mock}
}

// GetImageTagHistory provides a mock function with given fields: ctx, imageName, namespace
func (_m *MockImageService) GetImageTagHistory(ctx context.Context, imageName string, namespace string) (*models.ImageTagHistory, error) {
	ret := _m.Called(ctx, imageName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetImageTagHistory")
	}

	var r0 *models.ImageTagHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.ImageTagHistory, error)); ok {
		return rf(ctx, imageName, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.ImageTagHistory); ok {
		r0 = rf(ctx, imageName, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ImageTagHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, imageName, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageService_GetImageTagHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageTagHistory'
type MockImageService_GetImageTagHistory_Call struct {
	*mock.Call
}

// GetImageTagHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - imageName string
//   - namespace string
func (_e *MockImageService_Expecter) GetImageTagHistory(ctx interface{}, imageName interface{}, namespace interface{}) *MockImageService_GetImageTagHistory_Call {
	return &MockImageService_GetImageTagHistory_Call{Call: _e.mock.On("GetImageTagHistory", ctx, imageName, namespace)}
}

func (_c *MockImageService_GetImageTagHistory_Call) Run(run func(ctx context.Context, imageName string, namespace string)) *MockImageService_GetImageTagHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockImageService_GetImageTagHistory_Call) Return(_a0 *models.ImageTagHistory, _a1 error) *MockImageService_GetImageTagHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageService_GetImageTagHistory_Call) RunAndReturn(run func(context.Context, string, string) (*models.ImageTagHistory, error)) *MockImageService_GetImageTagHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetImages provides a mock function with given fields: ctx, namespace
func (_m *MockImageService) GetImages(ctx context.Context, namespace string) (*models.ImagesResponse, error) {
	ret := _m.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetImages")
	}

	var r0 *models.ImagesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.ImagesResponse, error)); ok {
		return rf(ctx, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.ImagesResponse); ok {
		r0 = rf(ctx, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ImagesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageService_GetImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImages'
type MockImageService_GetImages_Call struct {
	*mock.Call
}

// GetImages is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockImageService_Expecter) GetImages(ctx interface{}, namespace interface{}) *MockImageService_GetImages_Call {
	return &MockImageService_GetImages_Call{Call: _e.mock.On("GetImages", ctx, namespace)}
}

func (_c *MockImageService_GetImages_Call) Run(run func(ctx context.Context, namespace string)) *MockImageService_GetImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockImageService_GetImages_Call) Return(_a0 *models.ImagesResponse, _a1 error) *MockImageService_GetImages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageService_GetImages_Call) RunAndReturn(run func(context.Context, string) (*models.ImagesResponse, error)) *MockImageService_GetImages_Call {
	_c.Call.Return(run)
	return _c
}

// HandleImageEvent provides a mock function with given fields: event
func (_m *MockImageService) HandleImageEvent(event k8s.ImageEvent) {
	_m.Called(event)
}

// MockImageService_HandleImageEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleImageEvent'
type MockImageService_HandleImageEvent_Call struct {
	*mock.Call
}

// HandleImageEvent is a helper method to define mock.On call
//   - event k8s.ImageEvent
func (_e *MockImageService_Expecter) HandleImageEvent(event interface{}) *MockImageService_HandleImageEvent_Call {
	return &MockImageService_HandleImageEvent_Call{Call: _e.mock.On("HandleImageEvent", event)}
}

func (_c *MockImageService_HandleImageEvent_Call) Run(run func(event k8s.ImageEvent)) *MockImageService_HandleImageEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(k8s.ImageEvent))
	})
	return _c
}

func (_c *MockImageService_HandleImageEvent_Call) Return() *MockImageService_HandleImageEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockImageService_HandleImageEvent_Call) RunAndReturn(run func(k8s.ImageEvent)) *MockImageService_HandleImageEvent_Call {
	_c.Run(run)
	return _c
}

// NewMockImageService creates a new instance of MockImageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageService {
	mock := &MockImageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
